CREATE TABLE public.word_data (
    word_id integer NOT NULL,
    word_surah integer,
    word_ayah integer,
    word_page integer,
    word_number_in_quran integer,
    word_number_in_surah integer,
    word_number_in_ayah integer,
    word_type character varying(10) DEFAULT NULL::character varying,
    word_arabic character varying(40) DEFAULT NULL::character varying,
    word_transliteration character varying(40) DEFAULT NULL::character varying,
    word_translation character varying(100) DEFAULT NULL::character varying
);
ALTER TABLE public.word_data ALTER COLUMN word_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.word_data_word_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE ONLY public.word_data
    ADD CONSTRAINT word_data_pkey PRIMARY KEY (word_id);
CREATE INDEX "ARABIC" ON public.word_data USING btree (word_transliteration);
CREATE INDEX "AYAH" ON public.word_data USING btree (word_ayah, word_number_in_surah);
CREATE INDEX "ID" ON public.word_data USING btree (word_id, word_surah);
CREATE INDEX "SURAH" ON public.word_data USING btree (word_surah, word_ayah);
CREATE INDEX word_id ON public.word_data USING btree (word_id, word_surah, word_ayah, word_number_in_quran, word_number_in_surah, word_number_in_ayah, word_type);
CREATE INDEX word_number_in_quran ON public.word_data USING btree (word_number_in_quran);
