create table if not exists "word_data" (
    "word_id" int generated by default as identity not null,
    "word_surah" int default null,
    "word_ayah" int default null,
    "word_page" int default null,
    "word_number_in_quran" int default null,
    "word_number_in_surah" int default null,
    "word_number_in_ayah" int default null,
    "word_type" varchar(10) default null,
    "word_arabic" varchar(40) default null,
    "word_transliteration" varchar(40) default null,
    "word_translation" varchar(100) default null,
    primary key ("word_id")
  );
  create index "ARABIC" on "word_data"("word_transliteration");
  create index "ID" on "word_data"(
    "word_id",
    "word_surah"
  );
  create index "AYAH" on "word_data"(
    "word_ayah",
    "word_number_in_surah"
  );
  create index "SURAH" on "word_data"(
    "word_surah",
    "word_ayah"
  );
  create index "word_number_in_quran" on "word_data"("word_number_in_quran");
  create index "word_id" on "word_data"(
    "word_id",
    "word_surah",
    "word_ayah",
    "word_number_in_quran",
    "word_number_in_surah",
    "word_number_in_ayah",
    "word_type"
  );
